### ISSUE TITLE
Traceback when analysing jinja macros

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content-test-filtering#15]
python3 ./content_test_filtering.py pr --output-format markdown 7468
```
Traceback (most recent call last):
  File "/home/ggasparb/workspace/github/content-test-filtering/./content_test_filtering.py", line 44, in <module>
    diff_structure = diff_analysis.analyse_file(file_record)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/diff_analysis.py", line 54, in analyse_file
    return file_analyzer.process_analysis()
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/analysis/JinjaAnalysis.py", line 293, in process_analysis
    self.analyse_macros(changed_macros)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/analysis/JinjaAnalysis.py", line 156, in analyse_macros
    self.analyse_macros_in_rules(macros)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/analysis/JinjaAnalysis.py", line 117, in analyse_macros_in_rules
    del default_macros[macro.name]
KeyError: '_make_bash_variable_assignment'
```

**Comment by ggbecker** [comment]
This doesn't seem to be manifesting anymore:

```
python3 ./content_test_filtering.py pr --output-format markdown 7468
```

```
**Changes identified:**
Rules:
 audit_rules_file_deletion_events
 audit_rules_unsuccessful_file_modification
 audit_rules_kernel_module_loading
 audit_rules_kernel_module_loading_delete
 audit_rules_kernel_module_loading_finit
 audit_rules_kernel_module_loading_init
 audit_rules_suid_privilege_function
 audit_rules_time_clock_settime
 directory_access_var_log_audit
 audit_rules_networkconfig_modification
Macros:
 _make_bash_variable_assignment
 bash_firefox_cfg_setting
 bash_fix_audit_syscall_rule

<details>
<summary>Show details</summary>

Rule audit_rules_file_deletion_events:
 Templatization usage changed.
 Found change in bash remediation.
Rule audit_rules_unsuccessful_file_modification:
 Templatization usage changed.
 Found change in bash remediation.
Rule audit_rules_kernel_module_loading:
 Templatization usage changed.
 Found change in bash remediation.
Rule audit_rules_kernel_module_loading_delete:
 Templatization usage changed.
 Found change in bash remediation.
Rule audit_rules_kernel_module_loading_finit:
 Templatization usage changed.
 Found change in bash remediation.
Rule audit_rules_kernel_module_loading_init:
 Templatization usage changed.
 Found change in bash remediation.
Rule audit_rules_suid_privilege_function:
 Templatization usage changed.
 Found change in bash remediation.
Rule audit_rules_time_clock_settime:
 Templatization usage changed.
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule directory_access_var_log_audit:
 Templatization usage changed.
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule audit_rules_networkconfig_modification:
 Templatization usage changed.
 The rule doesn't occur in any profile nor product.
Macro _make_bash_variable_assignment:
 In Bash remediation for firefox_preferences-verification.
 In Bash remediation for firefox_preferences-javascript_status_bar_text.
 In Bash remediation for firefox_preferences-lock_settings_obscure.
 In Bash remediation for firefox_preferences-home_page.
 In Bash remediation for firefox_preferences-non-secure_page_warning.
 In Bash remediation for firefox_preferences-javascript_context_menus.
 In Bash remediation for firefox_preferences-javascript_window_resizing.
 In Bash remediation for firefox_preferences-ssl_version_2.
 In Bash remediation for firefox_preferences-autofill_passwords.
 In Bash remediation for firefox_preferences-addons_plugin_updates.
 In Bash remediation for firefox_preferences-password_store.
 In Bash remediation for firefox_preferences-auto-update_of_firefox.
 In Bash remediation for firefox_preferences-lock_settings_config_file.
 In Bash remediation for firefox_preferences-cookies_user_notice.
 In Bash remediation for firefox_preferences-shell_protocol.
 In Bash remediation for firefox_preferences-search_update.
 In Bash remediation for firefox_preferences-background_data.
 In Bash remediation for firefox_preferences-javascript_window_changes.
 In Bash remediation for firefox_preferences-autofill_forms.
 In Bash remediation for firefox_preferences-ssl_version_3.
 In Bash remediation for firefox_preferences-cookies_clear.
 In Bash remediation for firefox_preferences-development_tools.
 In Bash remediation for firefox_preferences-ssl_protocol_tls.
 In Bash remediation for firefox_preferences-javascript_status_bar_changes.
 In Bash remediation for firefox_preferences-install_extensions.
 In Bash remediation for firefox_preferences-auto-download_actions.
 In Bash remediation for firefox_preferences-pop-up_windows.
 In Bash remediation for firefox_preferences-open_confirmation.
Macro bash_firefox_cfg_setting:
 In Bash remediation for firefox_preferences-verification.
 In Bash remediation for firefox_preferences-javascript_status_bar_text.
 In Bash remediation for firefox_preferences-home_page.
 In Bash remediation for firefox_preferences-non-secure_page_warning.
 In Bash remediation for firefox_preferences-javascript_context_menus.
 In Bash remediation for firefox_preferences-javascript_window_resizing.
 In Bash remediation for firefox_preferences-ssl_version_2.
 In Bash remediation for firefox_preferences-autofill_passwords.
 In Bash remediation for firefox_preferences-addons_plugin_updates.
 In Bash remediation for firefox_preferences-password_store.
 In Bash remediation for firefox_preferences-auto-update_of_firefox.
 In Bash remediation for firefox_preferences-cookies_user_notice.
 In Bash remediation for firefox_preferences-shell_protocol.
 In Bash remediation for firefox_preferences-search_update.
 In Bash remediation for firefox_preferences-background_data.
 In Bash remediation for firefox_preferences-javascript_window_changes.
 In Bash remediation for firefox_preferences-autofill_forms.
 In Bash remediation for firefox_preferences-ssl_version_3.
 In Bash remediation for firefox_preferences-cookies_clear.
 In Bash remediation for firefox_preferences-development_tools.
 In Bash remediation for firefox_preferences-ssl_protocol_tls.
 In Bash remediation for firefox_preferences-javascript_status_bar_changes.
 In Bash remediation for firefox_preferences-install_extensions.
 In Bash remediation for firefox_preferences-auto-download_actions.
 In Bash remediation for firefox_preferences-pop-up_windows.
 In Bash remediation for firefox_preferences-open_confirmation.
Macro bash_fix_audit_syscall_rule:
 In Bash remediation for audit_rules_suid_privilege_function.
 In Bash remediation for audit_rules_kernel_module_loading.
 In Bash remediation for audit_rules_kernel_module_loading_delete.
 In Bash remediation for audit_rules_kernel_module_loading_init.
 In Bash remediation for audit_rules_kernel_module_loading_finit.
 In Bash remediation for audit_rules_time_clock_settime.
 In Bash remediation for audit_rules_unsuccessful_file_modification.
 In Bash remediation for directory_access_var_log_audit.
 In Bash remediation for audit_rules_file_deletion_events.
 In Bash remediation for audit_rules_networkconfig_modification.
</details>


**Recommended tests to execute:**
 build_product rhel8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_kernel_module_loading_finit
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_kernel_module_loading_init
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml directory_access_var_log_audit
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_file_deletion_events
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_time_clock_settime
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_kernel_module_loading
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_unsuccessful_file_modification
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_kernel_module_loading_delete
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_suid_privilege_function
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml audit_rules_networkconfig_modification
```
